name: Deploy IT Club Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: smkn21jakarta.sch.id
          username: smknjaka
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /home/smknjaka/repositories/it-club

            echo "Pull latest..."
            git pull origin main

            echo "Deploy..."
            uapi VersionControlDeployment create repository_root=/home/smknjaka/repositories/it-club

            echo "Done!"